__Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)__

In [1]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.07600632 0.11108492 0.58548937]
 [0.92116653 0.74949152 0.35486738]
 [0.77337418 0.82766767 0.90112083]
 [0.08177268 0.00747247 0.1870243 ]
 [0.31791445 0.71721353 0.12868757]]
Second array:
[[0.43939653 0.27938433]
 [0.33052491 0.12632233]
 [0.9349882  0.68609147]]
Dot product of two arrays:
[[0.61753891 0.43696675]
 [0.98427981 0.5955085 ]
 [1.45592006 0.93887286]
 [0.21326599 0.15210573]
 [0.4970688  0.26771185]]


__Given a 1D array, negate all elements which are between 3 and 8, in place__

x = np.array([1, 2, 3,<code>4, 5, 6, 7, 8</code>, 9, 10])

In [2]:
import numpy as np
x = np.array([1, 2, 3,4, 5, 6, 7, 8, 9, 10])


x[3:9] = np.multiply(x[3:9],-1)

print(x)

[ 1  2  3 -4 -5 -6 -7 -8 -9 10]


__What are the result of the following expressions?__

In [4]:
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0.)) 
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0.))

0
nan
nan
nan


<ipython-input-4-4f3a0242f6ff>:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-4-4f3a0242f6ff>:2: RuntimeWarning: invalid value encountered in floor_divide
  print(np.array(0) // np.array(0.))
<ipython-input-4-4f3a0242f6ff>:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-4-4f3a0242f6ff>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0.))


__Create a 2d array with 1 on the border and 0 inside__

In [ ]:
[1, 1, 1, 1, 1, 1
 1, 0, 0, 0, 0, 1
 1, 1, 1, 1, 1, 1]

In [6]:
import numpy as np
x = np.ones((5,5))

print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


__Create a random array of size 30 and find the mean value__

In [7]:
import numpy as np
x = np.random.randn(30)
print("Average of the array elements:")
mean = x.mean()
print(mean)

Average of the array elements:
0.05765920300400577


__Create a 10x10 array with random values and find the minimum and maximum values__

In [8]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.91160083 0.89951114 0.32148046 0.94320336 0.57943455 0.70583419
  0.3275281  0.35025591 0.86011722 0.26333729]
 [0.07149942 0.34691958 0.70458819 0.49917333 0.28688387 0.14640636
  0.25250267 0.53579949 0.83799133 0.40528635]
 [0.46782749 0.16276884 0.53172832 0.73602058 0.39941869 0.89054211
  0.97154966 0.35428993 0.50842699 0.20852547]
 [0.17261846 0.90074181 0.33855858 0.25106801 0.18436768 0.17373476
  0.89413101 0.01133282 0.34809171 0.7127191 ]
 [0.63810664 0.78767338 0.68989492 0.94271671 0.42149014 0.48869637
  0.41087083 0.4409224  0.45962399 0.71786191]
 [0.47722654 0.38209753 0.49617591 0.3074537  0.46477435 0.78415045
  0.17079126 0.98156222 0.1738382  0.91032116]
 [0.66006657 0.26793911 0.50490015 0.19846621 0.97098904 0.65872809
  0.14419619 0.26143449 0.90225554 0.54580014]
 [0.14409267 0.23658144 0.26311752 0.83470549 0.24100222 0.00738518
  0.2305804  0.12957826 0.52529339 0.66643245]
 [0.5970479  0.96197188 0.92882746 0.0626552  0.2700794  0.37349

__Create a 3x3x3 array with random values__

In [9]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.76119376 0.11612085 0.78795551]
  [0.37557652 0.84656421 0.7491595 ]
  [0.48775872 0.34273808 0.88548252]]

 [[0.83605494 0.41822026 0.54101538]
  [0.87211761 0.90272017 0.08039804]
  [0.86916294 0.25274198 0.67320932]]

 [[0.50131607 0.6872364  0.49749442]
  [0.99211125 0.49633822 0.35688592]
  [0.58698184 0.37562558 0.12840008]]]


__Create a 3x3 identity matrix___

In [11]:
import numpy as np
arr33=np.identity(3)
print('3x3 matrix:')
print(arr33)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


__Find indices of non­zero elements from [1,2,0,0,4,0]__

In [13]:
x = np.array([1,2,0,0,4,0])
print(np.nonzero(x))

(array([0, 1, 4], dtype=int64),)


__Reverse a Array__

In [14]:

import numpy as np
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


__Create a null array of size 10 but the fifth value which is 1__

In [15]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


__How to get the documentation of the numpy add function from the command line?__

In [17]:
import numpy as np
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

__Print the numpy version and the configuration__

In [18]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
None


__Create a array of size 10 with values ranging from 0 to 1, both excluded__

In [19]:
import numpy as np
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


__Consider two random array A anb B, check if they are equal__

In [21]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!!!!!!")
array_equal = np.allclose(x, y)
if(array_equal):
    print("they are equal")
else:
    print("they are not equal")

First array:
[0 1 0 1 0 0]
Second array:
[0 1 0 1 1 0]
Test above two arrays are equal or not!!!!!!
they are not equal


__Create a Matrix of random numbers with size 10000 and find the uniqueness of the generated numbers , also find the counts of the repeated numbers__

In [24]:
import numpy as np
x = np.random.randn(1000)
unique, counts = np.unique(x, return_counts=True)

print (np.asarray((unique, counts)).T)

[[-3.15911737  1.        ]
 [-2.74974643  1.        ]
 [-2.70956171  1.        ]
 ...
 [ 3.00585168  1.        ]
 [ 3.07246574  1.        ]
 [ 3.21409771  1.        ]]


__Create a vector of size 10 ranging from -1 to 1 and find the sine, cosine, sqrt, log, std of that vector__

In [36]:
import numpy as np
x = np.linspace(-1,1,12,endpoint=True)[1:-2]
print(x)
print(np.sin(x))
print(np.cos(x))
print(np.sqrt(x))
print(np.log(x))
print(std.cos(x))

[-0.81818182 -0.63636364 -0.45454545 -0.27272727 -0.09090909  0.09090909
  0.27272727  0.45454545  0.63636364]
[-0.72990422 -0.59427479 -0.43905397 -0.26935891 -0.09078392  0.09078392
  0.26935891  0.43905397  0.59427479]
[0.68354943 0.80426207 0.89846069 0.96303986 0.99587061 0.99587061
 0.96303986 0.89846069 0.80426207]
[       nan        nan        nan        nan        nan 0.30151134
 0.52223297 0.67419986 0.79772404]
[        nan         nan         nan         nan         nan -2.39789527
 -1.29928298 -0.78845736 -0.45198512]


<ipython-input-36-97a22c96df87>:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(x))
<ipython-input-36-97a22c96df87>:7: RuntimeWarning: invalid value encountered in log
  print(np.log(x))


NameError: name 'std' is not defined

Answered by : 
<a href="https://www.linkedin.com/in/saurabh-satapathy-692a6a1b9">Saurabh Satapathy</a> (AI ML BATCH)